FROM ubuntu:latest
COPY requirements.txt .
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN apt-get install -y uwsgi-plugin-python3
RUN apt-get install -y uwsgi-plugin-python
COPY http.ini .
EXPOSE 5000
ENTRYPOINT [ "uwsgi", "--ini", "http.ini"]